# my-ingestor-deployment-and-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ingestor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ingestor
  template:
    metadata:
      labels:
        app: my-ingestor
    spec:
      containers:
      - name: my-ingestor
        image: my_ingestor:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: my-ingestor-service
spec:
  selector:
    app: my-ingestor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
